### PR TITLE
SPIKE justfile or makefile for build scripts

### PR DESCRIPTION
**Pull request by cspotcode**
https://trello.com/c/kqNT3Pk4/29-spike-justfile-or-makefile-for-build-scripts

For the sake of demonstration, this PR includes both a `Makefile` *and* a `justfile`.  Once we choose which to use, just or make, we can delete the other, so that only one of them is merged to `main`.

To try them out:

```shell
just
make
just fmt
make fmt
just check
make check
```

This PR is stacked on top of the `update-dev-env-setup` branch, so it should not be merged till #9 is merged, and then this PR's target branch is changed to `main`

### CODE REVIEW

**Review by not-mike-smith — DISMISSED** [review]
I don't see much of a difference between the make an just files.  I don't know enough about either to have an opinion, unfortunately.  So I guess if one is more standard/common than the other, let's go with it.  Otherwise let's go with the one with better documentation?

**Comment by cspotcode** [comment]
> if one is more standard/common than the other, let's go with it.  Otherwise let's go with the one with better documentation?

Oh man, making it difficult for me.

I think makefiles are more common; they've been around for ages, so everyone has a joke about not understanding them and also has experience with them.

Justfiles have the better documentation since they have less gotchas and don't do make's file-based dependency tracking, so the readme is all you need.

Will wait till Dan's review.

**Comment by KaraThrash** [comment]
I'm with Mike on this one, I don't see the benefit but I also don't have a strong opinion which means I support Andrew's decision.

**Review by KaraThrash — DISMISSED** [review]

**Comment by cspotcode** [comment]
Sounds good, I'll go with the makefile since makefiles are more common.

**Review by KaraThrash — APPROVED** [review]
rubber stamping

**Pull request merged**
